ineuiit/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
import django.views.static
import news.views
import core.views
import collection.views

urlpatterns = [
    url(r'^$', news.views.home, name='home'),
    url(r'^search/$', core.views.search, name='search'),
    url(r'^news/$', news.views.news_list, name='news_list'),
    url(r'^announcements/$', news.views.announcements_list, name='announcements_list'),

    url(r'^news/(?P<slug>[\w-]+)/', news.views.news_obj, name='news_obj'),
    url(r'^announcements/(?P<slug>[\w-]+)/', news.views.announcements_obj, name='announcements_obj'),

    url(r'^rating/$', core.views.rating, name='rating'),
    url(r'^rating/statistic/(?P<obj_class>[\w-]+)_(?P<obj_id>\d+)/$', core.views.statistic, name='statistic'),

    url(r'^resource[/\w-]*/(?P<slug>[\w-]+)/$', collection.views.resource, name='resource'),
    url(r'^resource[/\w-]*/(?P<slug>[\w-]+)/(?P<slug_c>[\w-]+)$', collection.views.collection, name='collection'),

    url(r'^laporem/', include('laporem_field.urls', namespace='laporem')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^laporemComment/', include('laporem_comments.urls', namespace='laporemComments')),
    url(r'^ckeditor/', include ('ckeditor_uploader.urls')),
]


if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', django.views.static.serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
        url(r'^staticfiles/(?P<path>.*)$', django.views.static.serve, {
            'document_root': settings.STATIC_ROOT,
        }),
    ]

laporem_comments/urls.py
from django.conf.urls import include, url

import laporem_comments.views

urlpatterns = [
    url(r'^send/$', laporem_comments.views.send, name='send'),
    url(r'^delete/$', laporem_comments.views.delete, name='delete'),
]

laporem_comments/models.py
from django.db import models


class Comment(models.Model):
    url = models.TextField(null=True, editable=False)
    datetime = models.DateTimeField(auto_now_add=True)
    user = models.CharField(max_length=200, blank=True)
    text = models.TextField()

    class Meta:
        ordering = ['-datetime']

laporem_comments/views.py
from django.http import HttpResponse
from django.shortcuts import render

from laporem_comments.models import Comment


def send(request):
    if request.POST and request.is_ajax():
        user = request.POST.get('laporemCommentesName', "").strip()
        text = request.POST.get('laporemCommentesText', "").strip()
        url = request.META.get('HTTP_REFERER', "")
        newComment = Comment(
            user=user,
            text=text,
            url=url
        )
        newComment.save()
        return render(request, 'comments/comment.html', {
            'comment': newComment,
        })


def delete(request):
    if request.POST and request.is_ajax() and request.user.is_superuser:
        c = Comment.objects.get(id=request.POST.get('id', None))
        c.delete()
        return HttpResponse(status=200)
    return HttpResponse(status=500)

laporem_comments/templates/comments/comment.html
<div class="comment" id="comment_{{ comment.id }}">
    <div class="laporemCommentes__name">
        {% if comment.user %}
            {{ comment.user }}
        {% else %}
            Без имени
        {% endif %}

        {% if request.user.is_superuser %}
            <small><a onclick="deleteComment({{ comment.id }}, this)" href="#">Удалить</a></small>
        {% endif %}
    </div>
    <div class="laporemCommentes__date">{{ comment.datetime|date:"d E Yг. H:i:s" }}</div>
    <div class="laporemCommentes__text">
        {{ comment.text }}
    </div>
</div>

laporem_comments/templates/comments/index.html
<h1>Комментарии</h1>
<div class="laporemCommentes mt-3 mb-3">
    <div class="laporemCommentes__form">
        <form class="laporemCommentesForm">
            {% csrf_token %}
            <div class="form-group">
                <input class="form-control" type="text" name="laporemCommentesName" placeholder="Ваше имя">
            </div>
            <div class="form-group">
                <textarea required class="form-control" name="laporemCommentesText" placeholder="Введите текст сообщения" rows="5"></textarea>
            </div>
            <button type="submit" class="btn btn-outline-success">Отправить</button>
        </form>
    </div>
    <div class="listComments">
        {% for comment in comments %}
            {% include 'comments/comment.html' with comment=comment %}
        {% endfor %}
    </div>
</div>
<script>
    $('.laporemCommentesForm').submit(function () {
        var el = this;
        event.preventDefault();
        var form = $(this).serialize();
        $.ajax({
            type: "POST",
            url: '{% url 'laporemComments:send' %}',
            data: form,
            success: function (data){
                $('.listComments', $(el).closest('.laporemCommentes')).prepend(data);
                $('[name=laporemCommentesText]',el).val("")
            }
        });

        return false
    });

    function deleteComment(id, el) {
        event.preventDefault();
        $.ajax({
            type: "POST",
            url: '{% url 'laporemComments:delete' %}',
            data: {csrfmiddlewaretoken: '{{ csrf_token }}','id': id },
            success: function (){
                $(el).closest('.comment').remove()
            }
        });
        return false;
    }
</script>