ineuiit/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
import django.views.static
import news.views
import core.views
import collection.views

urlpatterns = [
    url(r'^$', news.views.home, name='home'),
    url(r'^search/$', core.views.search, name='search'),
    url(r'^news/$', news.views.news_list, name='news_list'),
    url(r'^announcements/$', news.views.announcements_list, name='announcements_list'),

    url(r'^news/(?P<slug>[\w-]+)/', news.views.news_obj, name='news_obj'),
    url(r'^announcements/(?P<slug>[\w-]+)/', news.views.announcements_obj, name='announcements_obj'),

    url(r'^rating/$', core.views.rating, name='rating'),
    url(r'^rating/statistic/(?P<obj_class>[\w-]+)_(?P<obj_id>\d+)/$', core.views.statistic, name='statistic'),

    url(r'^resource[/\w-]*/(?P<slug>[\w-]+)/$', collection.views.resource, name='resource'),
    url(r'^resource[/\w-]*/(?P<slug>[\w-]+)/(?P<slug_c>[\w-]+)$', collection.views.collection, name='collection'),

    url(r'^laporem/', include('laporem_field.urls', namespace='laporem')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^laporemComment/', include('laporem_comments.urls', namespace='laporemComments')),
    url(r'^ckeditor/', include ('ckeditor_uploader.urls')),
]


if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', django.views.static.serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
        url(r'^staticfiles/(?P<path>.*)$', django.views.static.serve, {
            'document_root': settings.STATIC_ROOT,
        }),
    ]

collection/models.py
import datetime
import os
from ckeditor.fields import RichTextField
from django.db import models
from django.urls import reverse
from laporem_field.forms import LaporemImageField
from laporem_field.models import LaporemImage
from pytils.translit import slugify
from autoslug import AutoSlugField
from ckeditor_uploader.fields import RichTextUploadingField

from core.models import Scale, Rating_Base


def get_file_path(instance, filename):
    ext = filename.split('.')[-1]
    name = filename.split('.')[0:-1]
    filename = "%s.%s" % (slugify(name), ext)
    return os.path.join('collections', filename)



def get_name(obj, name):
    name = ' |-- ' + obj.title + name
    if obj.parent:
        return get_name(obj.parent, name)
    return name


class ImageResurse(LaporemImage):
    pass


class Resource(Rating_Base):
    parent = models.ForeignKey('self', null=True, blank=True, verbose_name='Родительский ресурс')
    title = models.CharField(max_length=500, verbose_name="Заголовок", blank=True)
    slug = models.SlugField(max_length=255, unique=True)
    description = RichTextUploadingField(blank=True, verbose_name="Описание")
    slider = LaporemImageField(null=True, blank=True, laporem_model_file=ImageResurse, verbose_name="Изображения",
                               help_text="Галерея фото")

    def __str__(self):
        name = get_name(self, '')
        return name

    def get_absolute_url(self):
        return reverse('resource', args=[self.slug])

    def get_statistic(self):
        return self.collection_set.all()

    class Meta:
        verbose_name = 'Ресурс'
        verbose_name_plural = 'Ресурсы'
        ordering = ['title']


class Collection(models.Model):
    resource = models.ForeignKey(Resource)
    image = models.ImageField(upload_to=get_file_path, verbose_name="Фото", null=True, blank=True)
    file = models.FileField(upload_to=get_file_path, verbose_name="Файл", null=True, blank=True)
    title = models.CharField(max_length=500, verbose_name="Заголовок")
    description = RichTextUploadingField(blank=True, verbose_name="Описание")
    slug = AutoSlugField(populate_from='title', max_length=1000, unique_with=['id', ])
    date = models.DateTimeField(default=datetime.datetime.now, verbose_name="Дата")


    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Объект ресурса'
        verbose_name_plural = 'Объекты ресурса'

news/models.py
import datetime

from ckeditor_uploader.fields import RichTextUploadingField
from django.urls import reverse
from model_utils.managers import InheritanceManager
from autoslug import AutoSlugField
from ckeditor.fields import RichTextField
from django.db import models
from image_cropping import ImageRatioField
import os
from pytils.translit import slugify
from laporem_field.forms import LaporemImageField
from laporem_field.models import LaporemImage

from collection.models import Resource


def get_file_path(instance, filename):
    ext = filename.split('.')[-1]
    name = filename.split('.')[0:-1]
    filename = "%s.%s" % (slugify(name), ext)
    return os.path.join('news', filename)


class ImageNews(LaporemImage):
    pass


class Events(models.Model):
    title = models.CharField(max_length=500, verbose_name="Заголовок")
    description = RichTextUploadingField(blank=True, verbose_name="Описание")
    general_image = models.ImageField(upload_to=get_file_path, blank=True, verbose_name="Главное фото", null=True)
    cropping = ImageRatioField('general_image', '265x165', verbose_name="Обрезка для превью")
    slider = LaporemImageField(null=True, blank=True, laporem_model_file=ImageNews, verbose_name="Изображения",
                               help_text="Галерея фото")
    slug = AutoSlugField(populate_from='title', max_length=1000, unique_with=['id', ])
    date = models.DateTimeField(default=datetime.datetime.now, verbose_name="Дата")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Событие'
        verbose_name_plural = 'События'


class Content(models.Model):
    title = models.CharField(max_length=500, verbose_name="Заголовок", blank=True)
    description = RichTextUploadingField(blank=True, verbose_name="Описание")
    slider = LaporemImageField(null=True, blank=True, laporem_model_file=ImageNews, verbose_name="Изображения",
                               help_text="Галерея фото")
    slug = AutoSlugField(populate_from='title', max_length=1000, unique_with=['id', ])
    date = models.DateTimeField(default=datetime.datetime.now, verbose_name="Дата")
    parent = models.ForeignKey(Resource, null=True, blank=True, verbose_name='Относится к ресурсу')
    objects = InheritanceManager()

    class Meta:
        ordering = ['-date']

    def __str__(self):
        return self.title


class Banner(models.Model):
    image = models.ImageField(upload_to=get_file_path, verbose_name="Фото", null=True)
    url = models.CharField(blank=True, max_length=500)

    def __str__(self):
        return self.url

    class Meta:
        verbose_name = 'Банер'
        verbose_name_plural = 'Банеры'


class News(Content):

    def get_absolute_url(self):
        return reverse('news_obj', args=[self.slug])

    class Meta:
        verbose_name = 'Новость'
        verbose_name_plural = 'Новости'


class Announcement(Content):

    def get_absolute_url(self):
        return reverse('announcements_obj', args=[self.slug])

    class Meta:
        verbose_name = 'Анонс'
        verbose_name_plural = 'Анонсы'


class Page(Content):

    def get_absolute_url(self):
        return reverse('page_obj', args=[self.slug])

    class Meta:
        verbose_name = 'Анонс'
        verbose_name_plural = 'Анонсы'

collection/views.py
from django.shortcuts import render, get_object_or_404
from collection.models import Resource, Collection


def resource(request, slug):
    obj = get_object_or_404(Resource, slug=slug)
    collection_set = obj.collection_set.all()
    content_all = obj.content_set.all().select_subclasses()
    data = {
        'obj': obj,
        'collection_set': collection_set,
        'content_all': content_all
    }
    return render(request, 'resource/resource.html', data)


def collection(request, slug, slug_c):
    res = get_object_or_404(Resource, slug=slug)
    col = get_object_or_404(Collection, slug=slug_c, resource=res)
    data = {
        'obj': res,
        'col': col,
    }
    return render(request, 'resource/collection.html', data)

templates/resource/collection.html
{% extends 'resource/resource.html' %}
{% load block thumbnail %}

{% block title %}{{ col.title }}{% endblock %}
{% block description %}{{ col.description|striptags|nbsp_kill|truncatechars:'400' }}{% endblock %}

{% block right_block %}
    <div class="resource">

        <nav aria-label="breadcrumb" role="navigation">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'home' %}">Главная</a></li>
            {% include 'breadcrumb.html' with obj=obj %}
          </ol>
        </nav>

        <div class="title">
            {{ col.title }}
        </div>
        <div class="description">
            {{ col.description|safe }}
        </div>
        {% if col.file %}
            <div class="download">
                <a href="{{ col.file.url }}">Скачать {{ col.title|lower }}</a>
            </div>
        {% endif %}

    </div>
{% endblock %}

templates/resource/resource.html
{% extends 'pre_index.html' %}
{% load block thumbnail staticfiles comments %}

{% block title %}{{ obj.title }}{% endblock %}
{% block description %}{{ obj.description|striptags|nbsp_kill|truncatechars:'400' }}{% endblock %}


{% block dop_head %}
    <meta itemprop="name" content="{{ obj.title }}">
    <meta itemprop="image" content="{{ request.build_absolute_uri }}{{ obj.slider.first.file.url }}">
    <meta itemprop="description" content="{{ obj.description|striptags }}">
    <meta itemprop="url" content="{{ request.build_absolute_uri }}{% url 'resource' obj.slug %}">
    <meta property="og:title" content="{{ obj.title }}">
    <meta property="og:type" content="website">
    <meta property="og:description" content="{{ obj.description|striptags }}">
    <meta property="og:url" content="{{ request.build_absolute_uri }}{% url 'resource' obj.slug %}">
    <meta property="og:image" content="{{ request.build_absolute_uri }}{{ obj.slider.first.file.url }}">
{% endblock %}


{% block left_block %}
    <ul class="list-group childs">
        {% for child in obj.resource_set.all %}
            <li class="list-group-item child">
                <a href="{{ child.slug }}/">{{ child.title }}</a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

{% block right_block %}
    <div class="resource">
        <nav aria-label="breadcrumb" role="navigation">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'home' %}">Главная</a></li>
            {% include 'breadcrumb.html' with obj=obj %}
          </ol>
        </nav>

        <div class="">
            <link rel="stylesheet" type="text/css" href="{% static 'css/lightslider.min.css' %}"/>
            <link rel="stylesheet" type="text/css" href="{% static 'css/lightgallery.css' %}"/>
            <script src="{% static 'js/lightgallery.js' %}"></script>
            <script src="{% static 'js/lg-thumbnail.js' %}"></script>
            <script src="{% static 'js/lg-fullscreen.js' %}"></script>
            <script src="{% static 'js/lightslider.min.js' %}"></script>
            <script src="{% static 'js/slider_active.js' %}"></script>
            <script src="{% static 'js/lightgallery.js' %}"></script>

            {% include 'admin_controls.html' with obj=obj %}
        </div>

        <div class="">
            {% include  "news/innclude_slider.html" with obj=obj %}
        </div>

        <div class="title">
            {{ obj.title }}
        </div>

        <div class="description">
            {{ obj.description|safe }}

            <blockquote class="blockquote-reverse">
            <p>Поделиться ссылкой в социальных сетях</p>
            <footer class="like_tw_news">
                <script type="text/javascript" src="//yastatic.net/es5-shims/0.0.2/es5-shims.min.js" charset="utf-8"></script>
                <script type="text/javascript" src="//yastatic.net/share2/share.js" charset="utf-8"></script>
                <div class="ya-share2" data-services="vkontakte,facebook,odnoklassniki,moimir,gplus,twitter,lj,whatsapp"></div>
            </footer>
            </blockquote>



        </div>
        {% if obj.collection_set.all|length > 0 %}
            <div class="collections">
                {% csrf_token %}
                <div>
                    <div class="items">
                        <a class="item" href="{% url 'statistic' obj|model_class obj.id %}">Статистика</a>
                    </div>
                </div>
                {% for collection in obj.collection_set.all %}
                    <div class="collection row">
                        <div class="col-lg-3 image">
                            {% if collection.image %}
                                <a href="{% url 'collection' obj.slug collection.slug %}">
                                    <img src="{% thumbnail collection.image 300x300 %}">
                                </a>
                            {% endif %}
                            {% if obj.scale %}
                                {% get_rating request collection obj.scale %}
                            {% endif %}
                        </div>
                        <div class="col-lg-9">
                            <div class="">
                                <h3><a href="{% url 'collection' obj.slug collection.slug %}">{{ collection.title }}</a></h3>
                            </div>
                            <div class="description">
                                {{ collection.description|safe }}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% endif %}

        {% if obj.content_set.all|length > 0 %}
            <div class="content">
            <div class="news_anons row">
            {% for content in content_all %}
                <div class=" col-md-6">
                    <div class="new">
                        {% if content.slider|length > 0 %}
                            <div class="image">
                                <img src="{% thumbnail content.slider.first.file 100x100 %}">
                            </div>
                        {% endif %}
                        <span class="date">
                            {{ content.date|date:'d.m.Y' }}
                        </span>
                        <div class="title">
                            <a href="{{ content.get_absolute_url }}">{{ content.title }}</a>
                        </div>
                        <div class="description">
                            {{ content.description|striptags|nbsp_kill|safe|truncatewords:'50' }}
                        </div>
                    <div>
                        <a href="{{ content.get_absolute_url }}">
                            Подробнее
                        </a>
                    </div>
                    </div>
                </div>
            {% endfor %}
            </div>
            </div>
        {% endif %}


        {% comments request %}

    </div>
{% endblock %}


{% block dop_footer %}
    <script>
        $('.description img').each(function () {
            $(this).attr({
                'data-src': $(this).attr('src'),
            })
        })
        $('.description').lightGallery({
            'selector': 'img',
        });
    </script>
{% endblock %}

templates/resource/statistic.html
{% extends 'pre_index.html' %}
{% load block thumbnail staticfiles %}
{% load l10n %}
{% block title %}{% endblock %}
{% block description %}{% endblock %}

{% block left_block %}
{% endblock %}


{% block container %}
    <div class="container">
        <nav aria-label="breadcrumb" role="navigation">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'home' %}">Главная</a></li>
            {% include 'breadcrumb.html' with obj=obj %}
          </ol>
        </nav>

    {% if table_data %}
    <h2 class="text-center">
        {{ obj.title }}
    </h2>
    <div class="statistics">

            <div class="scripts">
                <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
                <script type="text/javascript">
                  google.charts.load('current', {'packages':['corechart']});
                  google.charts.setOnLoadCallback(drawChart);

                  function drawChart() {
                    var data = google.visualization.arrayToDataTable(
                        [
                                {% for obj in objs %}
                                    [
                                        {% for el in obj %}
                                            {%  if forloop.parentloop.first %}
                                                "{{ el }}"
                                            {% else %}
                                                {% if forloop.first %}
                                                        "{{ el|date:'d.m' }}"
                                                {% else %}
                                                    {{ el|unlocalize }}
                                                {% endif %}
                                            {% endif %}
                                            {% if not forloop.last %},{% endif %}
                                        {% endfor %}
                                    ]
                                    {% if not forloop.last %},{% endif %}
                                {% endfor %}
                        ]
                    );

                    var options = {
                      title: 'График изменения рейтинга',
                      hAxis: {title: 'Дата',  titleTextStyle: {color: '#333'}},
                      vAxis: {minValue: 0}
                    };

                    var chart = new google.visualization.AreaChart(document.getElementById('chart_div'));
                    chart.draw(data, options);
                  }
                </script>

            </div>
            <div id="chart_div" style="width: 100%; height: 500px;"></div>

        <div>

        <h2 class="text-center">
            Результат на сегодняшний день
        </h2>


        </div>
    </div>

    {% else %}

        <div class="jumbotron">
          <h1 class="display-4">К сожалению, на сегодняшний день нет проголосовавших :(</h1>
          <p class="lead">Вы можете стать первыми</p>
          <hr class="my-4">
          <p class="lead">
            <a class="btn btn-primary btn-lg" href="{% url 'resource' obj.slug %}" role="button">Перейти к голосованию</a>
          </p>
        </div>

    {% endif %}

    <table class="table">
        <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Название</th>
              <th scope="col">Средний балл</th>
              <th scope="col">Голосовать</th>
            </tr>
          </thead>
         <tbody>
            {% for o in table_data %}
                <tr>
                    <td>
                        {{ forloop.counter }}
                    </td>
                    <td>
                        {{ o.obj.title }}
                    </td>
                    <td>
                        {{ o.avg_result|floatformat:'2' }}
                    </td>
                    <td>
                        {% if o.obj.resource.scale %}
                            {% get_rating request o.obj o.obj.resource.scale %}
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
         </tbody>
        </table>

</div>
{% endblock %}